version: "2"

services:
  web:
    build: .
    command: python manage.py runserver 0:8080
    ports:
      - "8080:8080"
    volumes:
      - .:/web
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
